version: 0.2
phases:
    build:
        commands:
            - echo "Building the docker image"
            - docker build -t myapp .
            - docker images
            - echo "Saving Docker image as tar file"
            - docker save myapp:latest -o myapp.tar
artifacts:
    files:
        - myapp.tar
