version: 0.2

phases:
  build:
    commands:
      - echo "Current directory"
      - pwd

      - echo "Listing files"
      - ls -la

      - echo "Searching for tar file"
      - find . -name "*.tar"

      - echo "Loading docker image"
      - docker load -i myapp.tar

      - echo "Running docker container"
      - docker run myapp
