version: 0.2

phases:
  build:
    commands:
      - echo "Downloading image tar from S3"

      - aws s3 cp s3://vishnu-test-codebuild-batch/myapp.tar myapp.tar

      - echo "Loading Docker image"

      - docker load -i myapp.tar

      - echo "Running Docker container"

      - docker run myapp
